apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgBjys3gTvPHLRwqF9809LwFBzUnnbMOBw/E66Wrvd0rDdTmiS4O3EVmuCMf9EJyL1cnE4GPbY7qMB/8OKzL1OJC6Q3X6vB3YNesm9LBJG+v/Qz7bLRSYVqMc/WyLxGvlP4TDkzcGNDZ0qUI7TSv9fQSgmXPnvtXaOViWLvOguwmQPYhvSn9KsKWSOQoDPcqPJ++bFt5jo5+uFrKQwbV88O381F4hrHK2Lw75VmHMN+ZPjv/OIEetPfSNCWeRBK2I6D0iQLlp54qZ7ENqM2i13UNbKkNDKBy6rGBA5WvpDKAVM8p5jybsugJaDRlKNmk+aNmjM2RFvy2+CG33PdFk4f6gHQnop9NVVoAlXHlqoc3qoDlI2uGtC8ZjE/Da17eGx5bOQflCm0I51jZUubjAk+Vqb1cnFnWl0e/n8IsmKnEJXzKTK6cXN+IsfoSRB42MIcZZcozHVLF9YWCNlG2VWeLLnkvS9yWj+0h3k81KGbxdKRXsTZNh0QQocQ2VP2OM3TnPFUC1qgRcML3GIckhWa5QV7jt3JfXYGrNU8yZ9jBGBrEc0rhteGTPlubUMA7G9T4RM3hhKL7525VqXOEb3V6f8IIZvZZvXbjcj6Poi0GXrw1pZuM67tXlWo++o78U8TFXU9xhpehvGPgKqrxXI95WLe+iZ0dfd2XkJ9Vr28ZbX9nQdCil4+Prx72PAcXhVALwZkOM4orgggnIXmlRa6Qg6e0wTH4ZJkLgBJ1ayKPJ4DNe+24
    email: AgBNbM7yghDKkIy2Lob9e+bsrTI7TRfF+qanFki2rMFU4JxQZbBkRoW63ZVs8HFT/xPZqYHTb3p+ZynthXqOoUUpNxxNTW8fprIWUEZp5c2uTw6j3TFb8ClMj9W59BWMbvlIPwmq/X7ma/seCm7yZXEeLOH7+EisFBd4RQ7PeKw5C6P5vghDnyVafaqZpo92hS5Ox7mim79LyeUFPFNWK5Fv3G6nu8M4rTq7Jjc3zHL+RD0yHaomHXAj79/M+aCmMyvXX995s01VpCnv0y4q3uwnTZS5/Q0KDmcJCtcCS/7FF6UTbJ9RyZGuDJU3XYO8qibkq9g2oNEjOGBbXcUpUhNGhMvkKGKBbTb+SKoAW0g0ah5nI4JvxROCzO2qu18G+cUdv2KJgZ/qqkPehYjI0ZtoN3CyQmJYKQrPrOYfhGMJw8ZIwkxzM9NqzplX/3W2AIjvywSjQxh3DrHbI2CioEOssAcTKZv2w2r1Yg1JZN3XfaiKaUsVH6VW3JIBsLnInbfG3CYdn061+dPoxl4r3glPxfCqa3tJBFOnNKfI0PrZWs6iUABYeCdLn8HJDf1tBqtdJLhg6MT2DW79YMWk9y6i3sVltG1dkqWWFLWzIkUoc6cgCTruzMPGR49jOpWAJ3QQZbDNj7Z1rcDMZNhaHDjXUONg9b/+d6gS8LwaUlFohmtMISPyB8g9XbIHKrxWfPKKkZk1/vuw2skoVXfyrIcRc1i4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

