apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgCOsONJ0xyvan52z2WzibWkqbjzQLCG91NGAz0o3co9cbFHN/rSXV5l3ee6NRXg+Y0EwCVeFjlKFGVf3IjbeWghip70BLSONzaApkPqbYtRhIsR0S7u5OYOT5EDn/c11d9pB7IM0IHw+4IxZMRXbg+7YCKwIGcPPXciyc7KogV9jx0voGCwosaQilC5Vvqvf2+Sy3/CuVgNtGhAJ0N/Z+p3XtjLt5DA4dq+rzRJ5lR/AKRLS7ohGR3+Qh6ZCdniT4Cjuj54mWHyxF7OlQnPaWINH0yGnWJW/Ex7fBLYDi/B0nNJ1RLC/SvzvqEljJlFxAJXZnL6RfNXC0TXpqgpM2lFHfGZPfN5dzXFmreAhNYISiiU0EyXdmOl67tGRgU0Au51G73O5SIJCg6Ik+2xMujYenNmHZHXzTcXiwtseOsT84A3ne92DEUe0sKwUdhH4u5DJzJ+MsO1voeh9OJya6yHhNV6YHDQZE1GvNMJbBMMjbNrBEYOmv67cM0I/bEpDySxdSGeQRW/VDPmjSwwRSFBktwOjaYXrlW0yJ3VDrqP7MmxLL9D5frxzKrUs/rdEWkegoc9CT5As6IfBMDBIIDazCyaFikzJcM4mtwr+1HSjkEFtSS1HeiB5cgPAjXD6bcUTKaiAHFdJ+3Uqr+gKPyRWV7975WZZ7FOWQnmeDSiyVpbNJ2wfz1kUQoEl+DjyZ9xL7rV6dVp9ZoFzBqroJLw5Q315LZqEHlTMx+LsCs8B8Px3T7WDi2h
    email: AgDUKCZmrgJ36d+QKFtfMXPZCdVR4FW8mlSsOsj9pEVOqBWpVWUwAt4jjrywquAqWlxP7x8DijEfPwEAhSZuiL/Gz5y1wOYenX97R3sxqnXqzV/sMlUgEvKoT+5dEA+7shyeQqDxnZri0jOHLCbetZEDaDwT50klqk8p7Z5puQu+1D0H1teijwaKnXc0UN1LZm7hjF0vYwKorxHuC8StQKDYzv+kj2NZTt2WLRqvG9DOWMfaPhDme8MQP6L28woLS9fVg57ImaVtMCEJS0tPuzhB+kMAg7WoLYUWHKawoZK9LGgF250qZoph6QI6TNvAuVhMhCGTRcgDyZ2tpZvoO3v2MWxxlohTkWEArwGcXVY3z2hefoEDovaY4W9n5sG6zO1gSo/Uds58EZqoUu9YU55HPeOXz6zWMsEOMBV/VKBCn5xifeMF7rhIXv7kfFOMKSsm301b6qnwrFlfEe2mRPwtue8L0kMzguyuY3SeRKTxKTiQpFnNkAylKuy76e5yEZKDIFpddM+qGikIQtnuGB+J25nCZ/m0BXP7pPYqY4/ZqzldwZhN0u6jH5vmwMx3lGmy4rS8drxnBGnDBdk25u11qtvo8oDP2doUZBJBuhpd/mhnlj3D+938o8vCRQWVC+qBbXVZGQKuTAlCO9NPRL4CSga7ejVOkXPWPUZRa/eiSu9swTMJ2ZO1SS1yNFTxL5uxh9YlCLrGWqk2Ub9KE2rsjXfL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

