apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgADQNZwsB2iPRdnidcyoypWWNDoD/88mCwcXg773q3Jp+B9uP4ZtvyDOATXThgJHojaVfU70QknNxZxgzeMu2Q3NWIRlSN1KukeBTlqS7vB92QpAUVl3QVasDjofaIzTyCXZFH/sWcj4xQ9Xn2Q/gWHhpOldP2imCNPNm8DeqqgRDsY+B7vjFI+4EWRKvcbdf7GHC3r52fspgU78OcLiUozn4ltRIxW4KQp4YTci2ySncRSalVJgRnpjBQcUcSGW1GWAxO0MgN7ZJedT8N868UOyOPrcLJIhtIwn8b5E6UieX6HPr21iVWrN2Axm5JIslAAPVTIjAYAPrdRzx+2OHqlX72zryzLmwTvGLh9ripxZY6PWYvQb9yIfZ98Mr5K+foGiJT/f78fLbO4gLoDLv5BZ2+bjbG53kgA+wIk5ERqdLvw4R+6iemt9EyRGUtqs8w/TsZSo7JgYsR7n3g4mHJez2PqJYHQD5g1Nd2L1NPYcHGHGy/jgjINrtilYQtV8E1XoA80jYVCdd/Hee4doqFQVSkYFrObJAnU0yfpwp1HRdz1Pf6QVeO6S+jI2g+HIJYi9FvPBvNscRopI6oIeJIDYLkAibQLyKTMLoTx98Z9hsSEACtaiWq0cQex/aBzxEsTlXgItK8ri3BPvE3ZTwKqhG0AzUrYRcp9uoC8LXpGMXcDGKlwQ0r+fL67z60RAOSsjaTZ+pUS859Z8pP/DnobXiAS1hSMa0oEYlq5EzT1VkMAlKvn
    email: AgCC0ake9tchZfZEtXybCzb0C2MYCOKlErH7RsbuF42BkXLohiXr2EbCP7xWw93hXo6yJERI5X8AB0JQeymIAEBK/Fg1pYV8UupxUmpuViuUVyb3y0oKi3jl551b2uHTfrb/roBb492ZAqXivF/wcAN3OFJJyU5CnGRCCNBnSJPnzl31BcJPttzXfOCUQ9M/nK4LLRYlpTq31iA0bI4w6jBQols7l/ZeeWfQouDnZOvXn9SDHirlHGZPBbbgGV4CQH81G6u3//kCbN1v9mYerqBaCt042gDSgLU8Ll8wG1vwciKu7fBnDdMjzANCioD/okxTH6uMKL440DQCy9HuSOjqpNPLBcbWD6c0z0UqlbzVcp8KuQ7cnSzDh3Cfn24kS7iZeYedSmjz2SNz1uZUh34PvrUD1SgKzUwXBPkMGc15dGl2WGqxFW7CFycAqt6Rx+DnUjO/g+++DtpzFfSp2FR57mkW6NoPXMd1ZwFkQHAg2LZIH5zOvd0FA/TiPdQ5+yEsvVHA9ZWQ2tGCdXG8Ye3ucIj5ZXMvB/+1RxXDneANM/OtAPgkbmLGCfzxcGRTWgsrBTgOTIzrQZ2EdvEBe7lyzwxBD+XBvjmpiiyKr2zNO6yvSKRo4LiyuZtZ9l7xr8WzxS15WgN14hzRHOunit1H0jWwmXdN3b/t7gsnBR+rY8UNSE6aQFftFn+sJh5ETJVGMXbro6eFz2dBfB3hV8CTx86a
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

