apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgCg3TC7aN49Kfp3BrFD3+t0/lGtXXeKWv5hv1aJkqUueHlPGPStJhz0zFTLOVB3wL4cO0tDsq7MJx4TRKRaH+2Mz3Js/d+oh7AqfQR4F309UP4+bpn386u7q0vLtKmu4FG1zIGWoWMsyWxtQYuxwg6/fLvYEvOLxBuAtKGyg16lqCesJIWgar33m2Wycx3Sa/0r4UOvA0xGh9VfQFMBlfdoBqW9fMKXOZeRetB21iUUr5W2RXTvEQ7CajXhxuMsYIpcZtpmafa4d768MLWWm2yuB8fGXZ6pa5teY8roSETkjCJFA4LRb2hZvBRPhMG+Yl+ZD8X4i75vdxDv5yfWroKkuU8BaIOlQzZrYtNMwFO+7wj6GEkGCailrqNgVZrEMncgYRAMSuqRrT/cELDXY0uPEpZJ3Jd+VSaIcY7ouWD+zMuCPH6N0wSCoV+LaszjdUNcWL13ix05RJ1U+XgyT9dgO/sBhgsZkwuFCkb3U4zllaxyW0vC10vFQYrhLEfVacGG9Gjskvm8sh2YFAZoR1rGP9udEnKyHq9Q6bVTr6Vz2GSRldoRf0P/zSmOSiuqLzXmA9Z5GXGU06Ey2wFbHsQL7spWybaanrXcLmDAVD0GfO/KF7XflrT8pZCHQI6eA08HguWISVazYS8aS8get92O8iKo6iuaEasLy0l+dyXD4yimjdVCG8VnVKIdaz5kwBnqtldZQEmK4bejFj2KSHyfUe6sXazmW0eu880QKCS1HJVMP1wNnyk7
    email: AgBmY06epvFws+0G1nrxYQmogDH6syiuKk0k2W6CnOzgHQwEB5+DKV7yCBXafv104nbFOfM+vYG6zcXze2picd9b3vUGQ07n0En2ufNCUG5Q/N/WGDg5NP89Bwq4Fx/rVV7lWalkQVcMCY81BkSR7ad/ivhMZSr2mcR3k9n40CyUNDlM1LfwiXEpPRjXm4ROP/gVj6/UsQO/ClOnesGLgwzkbtR+l6VaXIp/XwteZvl0dhnbpr5jC1UNiFTj38aMjiSzLceE2L9gC1k5Ky68iAUfuC6xOU/PpuRlnLD+Q95Qawa88rejr0nlmZbLQ1La7WduOunQ+/KkD8qIJGa1oVjZVc+jGBNllgb9CzjObOC8BG9KtR4+zQaVU2Va057YmmK+aVLqerHoAGpSeXZbMhcHTkKNrUqUPuamS1ndniBn7sgNuu9ETsPxYU9brpHuYsIZvnLI3TR/GTZSYorpqPijGtL59PXm3xeMEjeKIPrbRYMvpgbMYvW0LI1i+AIBSv1cZyQbf8QaCr1r6pMMIP+lQH48MuGz4WqB08sWOnadWP74EFi5r7aFwoMrqpwWB4ynjFalitDckP3WuqEEX3Jod2yQe9mLw5YNzVFWTB8SJvkrWcpbOGmR14imMnZt8xSixEhgeXhSOn2ngVL9Wc6f6EE3W490DEj2NrpTeUb6eIrE2/QlkiX6N7I5LgjWrso4ryf4uwrZjl0Zg74OF2M4No1Y
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

