apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgAVOx13ohv6wXK2rVrHZ1iCje1W0/JlDDBxW584oNmAHoa+kr+136bCw64qFqK+9GeX5XniX4kVZBvBglFudQVyPAVkMEakaTN6g/M5/53ij0x1z0m6YZBaliA7xp9fAH9Ic8vBtulNDdyV2ip/CkLG+/th4y6rrED0H+yzP2EcfJqf5ElvagpCAsjewE1BoF6l5FSQSbjr751kr3RiF5p3JinWIFvTVUWS2qlEjjXGqCnOSG/uh4hDTw/DzBxdXBsQlq6qgguabPXyL70qTmOKD/vCkEsa9vCX1iWXpZlKQ/vu7SHtXqowLb5k4aYDpgENiy9tTNIXy/mUIBfOE7jdXgkE8G/9p5TGc6zxaokbHY+TNTXMSPn+7yRtY3Cdz/zD+cn+J6SqtZUvzhQAAtpMJNBFwhfcgaBdW8VzP6uTYJH3Qrhw62FQjdL2utxcFdlDADTp5lEastAXsDgqTYUOId5pR3eVT4l0grhppVZ2HdOtKesgAFfQN1hZUuAa80+kgh4W9o3e71lLZRypH0ShMqrC9nCE2pO1/pFPjxQwdu0M9KpDF4Npv/KyEFfjpb3A81wpXzplYH2ZQVkE2WpYTVdqH1fnOGlx72JZp11+d6NAfDDoIEUKgCqKRHFnmHQlnYxqABLOmdMSbEGZck0aylACtR7iRxIvIFijqqxD+5yEZLT1LBuSQ4wRckHTV4jNQeuSdaRSQL1COKMHCAG+gEH/8OtDM1M2UKoJehz52zn91YOfKcw2
    email: AgCVqGLgMoRlpKMOF8aZSOREZieBw8QQvgZXw9qeHMCEK6nceVpTWztfTA6UBN5TELyZjo9aovdpds5DJEkyw/tDapN+WqRsiQS5L7WXV1hIcWV8qJRzhRBXs6LTsoXzP5qZ9aFHukjGNOBo2ldopC0QwfRK/tTWJANhm5rRVDU85bgDGp0edBTOqMj86BNtTxOlSart2U0hLDkGGTyPY2vQ75RWs/drcjJj3jSjHM0vVsaKCkkgh6t4wrcFusT5W2oCuGAB+OsU0p9n6fPy59ZxzApp5Q/9IL7RaA1ZSBztleEOqj1F8NVY1eOBR1k4cr6OYSY4Qwaxcjd2VLFF9vTVTtzJTwcQfx50ndjtg7wUFMDXg48cRB2+xCQsgrD1vYMAKcEfG3iMN6cvEtvbAbuoQsJ2fJPqsmDqoaMIS9NUuGzFdZkKyEXTocartXX6/j3MIXwFgBbgv6ncAS/N5EHUJKvVgsoCJiKskko2MQtzU0vjwSFaq9CUrCUoxOGOyCEvu1mU1SYYPEq1q2c6/g4cYdGjYh1b4fovp54fK4EoDx72bKkHh0HQUmOQY76STBt2BBzzmInDMZZ0NNvZfA7xJjyJzonnm03xXS1+cnAog7GSitQYSIsOXTQHPqataQd6g6xDgMml/8uCoY/ZM9ew/AbB0pyxxUAly9TSvb7FaeywtvsBfkoQPRSQ4Ptb72PqLvUjeP2BD1T4ibPiUMQCFF9E
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

