apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
spec:
  releaseName: jackett
  chart:
    spec:
      chart: jackett
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/linuxserver/jackett
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteMany
        size: 1Gi