apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: heimdall
spec:
  chart:
    spec:
      version: "8.4.2"
  values:
    image:
      tag: 2.4.15
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    ingress:
      main:
        hosts:
          - host: portal.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific