apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/heimdall
  # - ../base/pirate-ship
patchesStrategicMerge:
  - podinfo-values.yaml
  - heimdall-values.yaml
  # - pirate-ship-values.yaml