apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  chart:
    spec:
      version: "16.3.2"
  values:
    image:
      tag: v4.1.0.6175
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    ingress:
      main:
        hosts:
          - host: radarr.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
