apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: pirate-ship
spec:
  values:
    image:
      tag: 4.2.4
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    persistence:
      media:
        volumeSpec:
          nfs:
            path: /mnt/Vault/kubernetes-staging/pirate-ship/Movies
            server: 10.0.0.50
    ingress:
      main:
        hosts:
          - host: radarr.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: pirate-ship
spec:
  values:
    image:
      tag: 3.0.9
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    persistence:
      media:
        volumeSpec:
          nfs:
            path: /mnt/Vault/kubernetes-staging/pirate-ship/TV
            server: 10.0.0.50
    ingress:
      main:
        hosts:
          - host: sonarr.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: pirate-ship
spec:
  values:
    image:
      tag: 0.20.2273
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    ingress:
      main:
        hosts:
          - host: jackett.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: pirate-ship
spec:
  values:
    image:
      tag: 3.00-r6-ls143
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    persistence:
      downloads:
        volumeSpec:
          nfs:
            path: /mnt/Vault/kubernetes-staging/pirate-ship/downloads
            server: 10.0.0.50
    ingress:
      main:
        hosts:
          - host: transmission.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: pirate-ship
spec:
  values:
    image:
      tag: 21.1.20221117
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    persistence:
      downloads:
        volumeSpec:
          nfs:
            path: /mnt/Vault/kubernetes-staging/pirate-ship/downloads
            server: 10.0.0.50
    ingress:
      main:
        hosts:
          - host: nzbget.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific