apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: pirate-ship
spec:
  chart:
    spec:
      version: "16.3.2"
  values:
    image:
      repository: ghcr.io/linuxserver/radarr
      tag: 4.2.4
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    ingress:
      main:
        hosts:
          - host: radarr.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: pirate-ship
spec:
  chart:
    spec:
      version: "16.3.2"
  values:
    image:
      repository: ghcr.io/linuxserver/sonarr
      tag: 3.0.9
    env:
      TZ: America/New_York
      PUID: "1003"
      PGID: "1002"
    ingress:
      main:
        hosts:
          - host: sonarr.staging.graytonward.com
            paths:
              - path: /
                pathType: ImplementationSpecific
