apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/metallb
  - ../base/longhorn
  - ../base/sealed-secrets
  - traefik-config.yaml
patchesStrategicMerge:
  - longhorn-values.yaml
  - sealed-secrets-values.yaml
  - metallb-values.yaml