apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/metallb
  - ipaddresspool.yaml
  - ../base/nginx
  - ../base/nfs-subdir-provisioner
patchesStrategicMerge:
  - nfs-values.yaml