apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/metallb
  - ../base/nfs-subdir-provisioner
  - ../base/traefik-config
  - ../base/sealed-secrets
patchesStrategicMerge:
  - nfs-values.yaml