apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: DEBUG
    ports:
        web:
          redirectTo: websecure
    additionalArguments:
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
      - --certificatesresolvers.cloudflare.acme.email=g-buddy@comcast.net
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --entrypoints.websecure.http.tls.domains[0].main=staging.graytonward.com
      - --entrypoints.websecure.http.tls.domains[0].sans=*.staging.graytonward.com
    persistence:
      enabled: true
      path: /certs
      size: 128Mi
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-api-credentials
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-api-credentials
    