apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    initContainers:
      - name: volume-permissions 
        image: busybox:1.31.1 
        command: ["sh", "-c", "chmod -Rv 600 /certs/*"] 
        volumeMounts: 
          - name: certs 
            mountPath: /certs 
    ingressRoutes:
      dashboard:
        enabled: false
    ports:
        web:
          redirectTo: websecure
    additionalArguments:
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
      - --certificatesresolvers.cloudflare.acme.email=g-buddy@comcast.net
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --entrypoints.websecure.http.tls.domains[0].main=staging.graytonward.com
      - --entrypoints.websecure.http.tls.domains[0].sans=*.staging.graytonward.com
    persistence:
      enabled: true
      path: /certs
      size: 128Mi
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-api-credentials
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-api-credentials
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`traefik.staging.graytonward.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService