apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: heimdall
spec:
  releaseName: heimdall
  chart:
    spec:
      chart: heimdall
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteMany
        size: 1Gi